name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Tymczasowe użycie starszej wersji

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install HTMLProofer
        run: gem install html-proofer

      - name: Check HTML
        run: htmlproofer ./ --allow-hash-href --check-html --disable-external
