name: CICD - HTMLProofer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Określenie wersji Node.js na 20

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install HTMLProofer
        run: gem install html-proofer

      - name: Check HTML
        run: htmlproofer ./ --allow-hash-href --check-html
